
# services:
#   frontend:
#     build:
#       context: ./frontend
#     volumes:
#       - ./app/build:/usr/share/nginx/html  # Front-end build files will be served by Nginx
#     depends_on:
#       - backend

#   backend:
#     build:
#       context: ./backend
#     ports:
#       - "5500:5500"

#   nginx:
#     image: nginx:alpine
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro  
#       - ./app/build:/usr/share/nginx/html  # Serve front-end files
#     ports:
#       - "8080:80"
#     depends_on:
#       - frontend
#       - backend

version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/build:/app/build  
    command: ["npm", "run", "build"]
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5500:5500"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount Nginx config file
      - ./frontend/build:/usr/share/nginx/html  # Serve frontend files
    ports:
      - "8080:80"  # Expose Nginx on port 8080
    depends_on:
      - frontend
      - backend
